services:
  # trackforge-api:
  #   image: ghcr.io/thomas-god/trackforge-api:latest
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.services.trackforge-api.loadbalancer.server.port=9002"
  #     - "traefik.http.routers.trackforge-api.rule=Host(`trackforge.fr`) && PathPrefix(`/api`)"
  #     - "traefik.http.routers.trackforge-api.entrypoints=websecure"
  #     - "traefik.http.routers.trackforge-api.tls.certresolver=myresolver"
  #   deploy:
  #     update_config:
  #       order: start-first

  trackforge-client:
    image: ghcr.io/thomas-god/trackforge-client:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.trackforge-client.loadbalancer.server.port=80"
      - "traefik.http.routers.trackforge-client.rule=Host(`trackforge.fr`)"
      - "traefik.http.routers.trackforge-client.entrypoints=websecure"
      - "traefik.http.routers.trackforge-client.tls.certresolver=myresolver"

volumes:
  letsencrypt:

networks:
  traefik-public:
    external: true
