services:
  trackforge-api:
    image: ghcr.io/thomas-god/trackforge-api:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.trackforge-api.loadbalancer.server.port=8000"
      - "traefik.http.routers.trackforge-api.rule=Host(`trackforge.fr`) && PathPrefix(`/api`)"
      - "traefik.http.routers.trackforge-api.entrypoints=websecure"
      - "traefik.http.routers.trackforge-api.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public
    volumes:
      - assets:/app/assets
    environment:
      ENV: production
      NASA_USER_FILE: /run/secrets/trackforge_nasa_user
      NASA_PWD_FILE: /run/secrets/trackforge_nasa_pwd
      NASA_URL_FILE: /run/secrets/trackforge_nasa_url
      ASSETS: /app/assets/elevation
    secrets:
      - trackforge_nasa_user
      - trackforge_nasa_pwd
      - trackforge_nasa_url
    deploy:
      update_config:
        order: start-first

  trackforge-client:
    image: ghcr.io/thomas-god/trackforge-client:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.trackforge-client.loadbalancer.server.port=80"
      - "traefik.http.routers.trackforge-client.rule=Host(`trackforge.fr`)"
      - "traefik.http.routers.trackforge-client.entrypoints=websecure"
      - "traefik.http.routers.trackforge-client.tls.certresolver=myresolver"
      - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

volumes:
  assets:

secrets:
  trackforge_nasa_user:
    external: true
  trackforge_nasa_pwd:
    external: true
  trackforge_nasa_url:
    external: true

networks:
  traefik-public:
    external: true
