name: Build api and client images

on:
  push:
    branches:
      - main

jobs:

  build-client-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:client"
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/thomas-god/trackforge-client:latest
            ghcr.io/thomas-god/trackforge-client:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-client-docker-image
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Stack Deploy
      uses: cssnr/stack-deploy-action@v1
      with:
        name: trackforge
        file: docker-stack.yaml
        host: trackforge.fr
        user: deploy
        ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
